# Generated by Django 4.1.5 on 2023-03-26 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(db_column='division_id', primary_key=True, serialize=False)),
                ('division', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LocalBrand',
            fields=[
                ('id', models.AutoField(db_column='local_brand_id', primary_key=True, serialize=False)),
                ('local_brand_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_code', models.CharField(db_column='brand_code', max_length=100, primary_key=True, serialize=False)),
                ('global_brand_name', models.CharField(blank=True, max_length=200, null=True)),
                ('upc_ean_gtin', models.CharField(blank=True, max_length=200, null=True)),
                ('division', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.division')),
                ('local_brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='brands.localbrand')),
            ],
        ),
    ]
