# Generated by Django 4.1.5 on 2023-05-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
