# Generated by Django 4.1.5 on 2023-05-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_brand_brand_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brand_name',
        ),
    ]
