# Generated by Django 4.1.5 on 2023-03-26 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('projects', '0001_initial'),
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAnalytics',
            fields=[
                ('product', models.OneToOneField(db_column='product_name', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.product')),
                ('utm_source', models.CharField(choices=[('PackPrimary', 'PackPrimary'), ('PackSecondary', 'PackSecondary'), ('PackSamples', 'PackSamples'), ('Stickers', 'Stickers'), ('OOH', 'OOH'), ('DOOH', 'DOOH'), ('POS', 'POS'), ('PrintMedia', 'PrintMedia'), ('TV', 'TV'), ('Insert', 'Insert'), ('DirectMail', 'DirectMail'), ('DeliveryBox', 'DeliveryBox'), ('Leaflet', 'Leaflet'), ('OnlineVideo', 'OnlineVideo')], max_length=100)),
                ('utm_medium', models.CharField(choices=[('QR', 'QR'), ('RFID', 'RFID'), ('NFC', 'NFC')], max_length=4)),
                ('utm_term', models.CharField(blank=True, max_length=200, null=True)),
                ('brand', models.ForeignKey(db_column='brand_code', on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
                ('project', models.OneToOneField(db_column='project_name', on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name': 'google analytics',
                'verbose_name_plural': 'google analytics',
            },
        ),
    ]
