# Generated by Django 4.1.5 on 2023-05-11 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_remove_campaignadditionaldetails_asset_image_with_qr_code_and_more'),
        ('analytics', '0002_alter_googleanalytics_utm_medium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleanalytics',
            name='project',
        ),
        migrations.AddField(
            model_name='googleanalytics',
            name='campaign',
            field=models.ForeignKey(db_column='campaign_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign'),
        ),
    ]
