# Generated by Django 4.1.5 on 2023-06-06 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0015_rename_activity_type_activity_experience_type_and_more'),
        ('campaigns', '0009_rename_utm_term_campaignadditionaldetails_variant_and_more'),
        ('analytics', '0006_delete_googleanalytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_placement', models.CharField(choices=[('PackPrimary', 'PackPrimary'), ('PackSecondary', 'PackSecondary'), ('PackSamples', 'PackSamples'), ('Stickers', 'Stickers'), ('OOH', 'OOH'), ('DOOH', 'DOOH'), ('POS', 'POS'), ('PrintMedia', 'PrintMedia'), ('TV', 'TV'), ('Insert', 'Insert'), ('DirectMail', 'DirectMail'), ('DeliveryBox', 'DeliveryBox'), ('Leaflet', 'Leaflet'), ('OnlineVideo', 'OnlineVideo')], max_length=100)),
                ('code_type', models.CharField(choices=[('AQR', 'AQR'), ('QR', 'QR'), ('RFID', 'RFID'), ('NFC', 'NFC')], max_length=13)),
                ('variant', models.CharField(blank=True, max_length=200, null=True)),
                ('brand', models.ForeignKey(db_column='brand_code', on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
                ('campaign', models.ForeignKey(db_column='campaign_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('product', models.ForeignKey(db_column='product_name', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'google analytics',
                'verbose_name_plural': 'google analytics',
            },
        ),
    ]
