# Generated by Django 4.1.5 on 2023-03-30 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('products', '0004_alter_salesdata_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=500)),
                ('key_contact_first_name', models.CharField(max_length=500)),
                ('key_contact_last_name', models.CharField(max_length=500)),
                ('key_contact_email_address', models.EmailField(max_length=254)),
                ('secondary_contact_first_name', models.CharField(blank=True, max_length=500, null=True)),
                ('secondary_contact_last_name', models.CharField(blank=True, max_length=500, null=True)),
                ('secondary_contact_email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_added', models.DateField(auto_now=True)),
                ('date_updated', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignAdditionalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_brand_name', models.CharField(blank=True, max_length=500, null=True)),
                ('upc_ean_gtin', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(choices=[('Cosmetics', 'Cosmetics'), ('Grocery', 'Grocery'), ('Snacks', 'Snacks'), ('Medicines', 'Medicines')], max_length=100)),
                ('landing_page_url', models.URLField()),
                ('is_landing_page_on_an_external_third_party_site', models.BooleanField(default=False)),
                ('does_landing_page_include_1pd_capture_or_signup', models.BooleanField(default=False)),
                ('does_landing_page_include_option_to_purchase', models.BooleanField(default=False)),
                ('if_yes_is_there_an_incentive_to_purchase', models.BooleanField(default=False)),
                ('estimated_total_or_annual_unit_volume', models.IntegerField()),
                ('planned_launch_date', models.DateField()),
                ('utm_source', models.CharField(choices=[('PackPrimary', 'PackPrimary'), ('PackSecondary', 'PackSecondary'), ('PackSamples', 'PackSamples'), ('Stickers', 'Stickers'), ('OOH', 'OOH'), ('DOOH', 'DOOH'), ('POS', 'POS'), ('PrintMedia', 'PrintMedia'), ('TV', 'TV'), ('Insert', 'Insert'), ('DirectMail', 'DirectMail'), ('DeliveryBox', 'DeliveryBox'), ('Leaflet', 'Leaflet'), ('OnlineVideo', 'OnlineVideo')], max_length=100)),
                ('code_placement', models.CharField(choices=[('FOP', 'Front of pack'), ('BOP', 'Back of pack'), ('SOP', 'Side of pack'), ('Lid', 'Lid'), ('Sticker', 'Sticker'), ('BackingCard', 'BackingCard'), ('Insert', 'Insert'), ('OuterFOP', 'Outer front of pack'), ('OuterBOP', 'Outer Back of Pack'), ('InsidePack', 'InsidePack'), ('POS', 'Point of Sale'), ('PrintAd', 'PrintAd')], max_length=100)),
                ('utm_medium', models.CharField(choices=[('QR', 'QR'), ('RFID', 'RFID'), ('NFC', 'NFC')], max_length=4)),
                ('utm_campaign', models.CharField(max_length=200)),
                ('utm_term', models.CharField(max_length=200)),
                ('utm_content', models.CharField(max_length=200)),
                ('final_tagged_landing_page_url', models.URLField()),
                ('ga_profile_id', models.CharField(blank=True, max_length=500, null=True)),
                ('asset_image_with_qr_code', models.FileField(blank=True, null=True, upload_to='asset_images_with_qr_code/')),
                ('code_url', models.URLField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.activity')),
                ('brand_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.division')),
                ('local_brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.localbrand')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.market')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
