# Generated by Django 4.1.5 on 2023-03-31 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='updated_by',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
