# Generated by Django 4.1.5 on 2023-03-31 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_updated_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignadditionaldetails',
            options={'verbose_name': 'campaign additional details', 'verbose_name_plural': 'campaign additional details'},
        ),
    ]
