# Generated by Django 4.1.5 on 2023-05-10 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_alter_campaignadditionaldetails_utm_medium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignadditionaldetails',
            name='asset_image_with_qr_code',
        ),
        migrations.RemoveField(
            model_name='campaignadditionaldetails',
            name='estimated_total_or_annual_unit_volume',
        ),
    ]
