# Generated by Django 4.1.5 on 2023-06-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_rename_utm_term_campaignadditionaldetails_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignadditionaldetails',
            name='code_position',
            field=models.CharField(choices=[('FOP', 'Front of pack'), ('BOP', 'Back of pack'), ('SOP', 'Side of pack'), ('Lid', 'Lid'), ('Sticker', 'Sticker'), ('BackingCard', 'BackingCard'), ('Insert', 'Insert'), ('OuterFOP', 'Outer front of pack'), ('OuterBOP', 'Outer Back of Pack'), ('InsidePack', 'InsidePack'), ('POS', 'Point of Sale'), ('PrintAd', 'PrintAd')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaignadditionaldetails',
            name='code_type',
            field=models.CharField(choices=[('AQR', 'AQR'), ('QR', 'QR'), ('RFID', 'RFID'), ('NFC', 'NFC')], max_length=13, null=True),
        ),
    ]
