# Generated by Django 4.1.5 on 2023-06-09 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_campaignadditionaldetails_code_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignadditionaldetails',
            name='brand_code',
        ),
        migrations.RemoveField(
            model_name='campaignadditionaldetails',
            name='code_placement',
        ),
        migrations.RemoveField(
            model_name='campaignadditionaldetails',
            name='code_position',
        ),
        migrations.RemoveField(
            model_name='campaignadditionaldetails',
            name='code_type',
        ),
        migrations.RemoveField(
            model_name='campaignadditionaldetails',
            name='code_url',
        ),
        migrations.RemoveField(
            model_name='campaignadditionaldetails',
            name='final_tagged_landing_page_url',
        ),
        migrations.RemoveField(
            model_name='campaignadditionaldetails',
            name='ga_profile_id',
        ),
        migrations.RemoveField(
            model_name='campaignadditionaldetails',
            name='global_brand_name',
        ),
        migrations.RemoveField(
            model_name='campaignadditionaldetails',
            name='landing_page_url',
        ),
        migrations.RemoveField(
            model_name='campaignadditionaldetails',
            name='local_brand_name',
        ),
        migrations.RemoveField(
            model_name='campaignadditionaldetails',
            name='upc_ean_gtin',
        ),
        migrations.RemoveField(
            model_name='campaignadditionaldetails',
            name='utm_campaign',
        ),
        migrations.RemoveField(
            model_name='campaignadditionaldetails',
            name='utm_content',
        ),
        migrations.RemoveField(
            model_name='campaignadditionaldetails',
            name='variant',
        ),
    ]
