# Generated by Django 4.1.5 on 2023-03-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmarketdetails',
            name='is_default_market',
            field=models.BooleanField(default=False),
        ),
    ]
