# Generated by Django 4.1.5 on 2023-03-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productmarketdetails_is_default_market'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='utm_campaign',
        ),
        migrations.RemoveField(
            model_name='product',
            name='utm_content',
        ),
        migrations.AddField(
            model_name='productmarketdetails',
            name='utm_campaign',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmarketdetails',
            name='utm_content',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
