# Generated by Django 4.1.5 on 2023-03-26 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_utm_campaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='product',
            field=models.ForeignKey(db_column='product_name', on_delete=django.db.models.deletion.CASCADE, to='products.productmarketdetails'),
        ),
    ]
