# Generated by Django 4.1.5 on 2023-05-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qr_code_img',
            field=models.FileField(blank=True, null=True, upload_to='products_qr_codes/'),
        ),
    ]
