# Generated by Django 4.1.5 on 2023-05-24 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_remove_brand_brand_name'),
        ('products', '0007_alter_productmarketdetails_launch_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningDashboardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_attributed_incremental_sales_volume', models.IntegerField()),
                ('purchase_price', models.IntegerField()),
                ('products_category', models.CharField(choices=[('Cosmetics', 'Cosmetics'), ('Grocery', 'Grocery'), ('Snacks', 'Snacks'), ('Medicines', 'Medicines')], max_length=100)),
                ('cookie', models.CharField(max_length=150)),
                ('data', models.CharField(max_length=500)),
                ('dev_scans_data_4', models.CharField(max_length=500)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.activity')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.division')),
                ('local_brands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.localbrand')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.market')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('product_market_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productmarketdetails')),
                ('product_salesdata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.salesdata')),
            ],
        ),
    ]
