# Generated by Django 4.1.5 on 2023-05-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_planningdashboarddetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeCutomizationTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_color', models.CharField(max_length=10)),
                ('qr_code_logo_image', models.FileField(blank=True, null=True, upload_to='products_qr_codes')),
                ('qr_code_eye_shape', models.FileField(upload_to='products_qr_codes')),
                ('qr_code_background_color', models.CharField(default='#000000', max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='planningdashboarddetails',
            options={'verbose_name': 'Planning Dashboard Details', 'verbose_name_plural': 'Planning Dashboard Details'},
        ),
    ]
