# Generated by Django 4.1.5 on 2023-05-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_qrcodecutomizationtemplates_sample_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcodecutomizationtemplates',
            options={'verbose_name': 'QR Code Cutomization Templates', 'verbose_name_plural': 'QR Code Cutomization Templates'},
        ),
        migrations.AddField(
            model_name='qrcodecutomizationtemplates',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='qrcodecutomizationtemplates',
            name='qr_code_eye_shape',
            field=models.CharField(max_length=100),
        ),
    ]
