# Generated by Django 4.1.5 on 2023-05-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_qrcodecutomizationtemplates_sample_qr_code_blob_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodecutomizationtemplates',
            name='template_name',
            field=models.CharField(default='QR Code Sample Template', max_length=100),
        ),
    ]
