# Generated by Django 4.1.5 on 2023-06-06 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_rename_utm_term_campaignadditionaldetails_variant_and_more'),
        ('products', '0014_qrcodecutomizationtemplates_template_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity_type',
            new_name='experience_type',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='code_placement',
            new_name='code_position',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='qr_code_img_blob_url',
            new_name='customized_qr_code_img_blob_url',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='budget_holder',
            new_name='requester_email',
        ),
        migrations.RenameField(
            model_name='productmarketdetails',
            old_name='launch_volume',
            new_name='estimated_annual_units',
        ),
        migrations.RenameField(
            model_name='productmarketdetails',
            old_name='launch_date',
            new_name='expected_launch_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qr_code_img',
        ),
        migrations.RemoveField(
            model_name='productmarketdetails',
            name='utm_campaign',
        ),
        migrations.AddField(
            model_name='planningdashboarddetails',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='product',
            name='campaign_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='product',
            name='qr_code_img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
