# Generated by Django 4.1.5 on 2023-06-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_rename_activity_type_activity_experience_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmarketdetails',
            name='utm_campaign',
            field=models.CharField(default='Test', max_length=200),
            preserve_default=False,
        ),
    ]
