# Generated by Django 4.1.5 on 2023-06-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_productmarketdetails_utm_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_id_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
