# Generated by Django 4.1.5 on 2023-06-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_short_id_product_short_id_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmarketdetails',
            name='estimated_annual_units',
            field=models.CharField(max_length=100),
        ),
    ]
